name: Python checks

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/python-checks.yml
      - pyproject.toml

jobs:
  checks:
    name: Python checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run flake8
        run: |
          poetry run flake8 --ignore=E501 flickrknob/*.py
      - name: Run pylint
        run: |
          poetry run pylint flickrknob/*.py
      - name: Run black in check mode
        run: |
          poetry run black --check flickrknob/*.py
      - name: Run isort in check mode
        run: |
          poetry run isort flickrknob/*.py  --check --diff
