name: Python checks

on:
  push:
    paths:
      - "**.py"

jobs:
  checks:
    name: Python checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run flake8
        run: |
          pip install flake8
          flake8 **/*.py
      - name: Run pylint
        run: |
          pip install pylint
          pylint **/*.py
